export const aspectLabels = {
  air: 'Aer',
  earth: 'Terra',
  fire: 'Ignis',
  water: 'Aqua',
  order: 'Ordo',
  entropy: 'Perditio',
  void: 'Vacuos',
  light: 'Lux',
  energy: 'Potentia',
  motion: 'Motus',
  life: 'Victus',
  weather: 'Tempestas',
  cold: 'Gelum',
  crystal: 'Vitreus',
  death: 'Mortuus',
  flight: 'Volatus',
  darkness: 'Tenebrae',
  soul: 'Spiritus',
  poison: 'Venenum',
  eldritch: 'Alienis',
  magic: 'Praecantatio',
  aura: 'Auram',
  taint: 'Vitium',
  plant: 'Herba',
  beast: 'Bestia',
  undead: 'Exanimis',
  mind: 'Cognitio',
  senses: 'Sensus',
  man: 'Humanus',
  metal: 'Metallum',
  tool: 'Instrumentum',
  aversion: 'Aversio',
  protect: 'Praemunio',
  hunger: 'Fames',
  greed: 'Lucrum',
  desire: 'Desiderium',
  craft: 'Fabrico',
  mechanism: 'Machina',
  trap: 'Vinculum',
  exchange: 'Permutatio',
  electricity: 'Electrum',
  magnetism: 'Magneto',
  cheatiness: 'Nebrisum',
  radioactivity: 'Radio',
  stupidity: 'Strontio',
}

export const aspectKeysByTag = {
  aer: 'air',
  terra: 'earth',
  ignis: 'fire',
  aqua: 'water',
  ordo: 'order',
  perditio: 'entropy',
  vacuos: 'void',
  lux: 'light',
  potentia: 'energy',
  motus: 'motion',
  victus: 'life',
  tempestas: 'weather',
  gelum: 'cold',
  vitreus: 'crystal',
  mortuus: 'death',
  volatus: 'flight',
  tenebrae: 'darkness',
  spiritus: 'soul',
  venenum: 'poison',
  alienis: 'eldritch',
  praecantatio: 'magic',
  auram: 'aura',
  vitium: 'taint',
  herba: 'plant',
  bestia: 'beast',
  exanimis: 'undead',
  cognitio: 'mind',
  sensus: 'senses',
  humanus: 'man',
  metallum: 'metal',
  instrumentum: 'tool',
  aversio: 'aversion',
  praemunio: 'protect',
  fames: 'hunger',
  lucrum: 'greed',
  desiderium: 'desire',
  fabrico: 'craft',
  machina: 'mechanism',
  vinculum: 'trap',
  permutatio: 'exchange',
  electrum: 'electricity',
  magneto: 'magnetism',
  nebrisum: 'cheatiness',
  radio: 'radioactivity',
  strontio: 'stupidity',
}

export const gtnhAspectData = {
  base: ['air', 'earth', 'fire', 'water', 'order', 'entropy'],
  compounds: {
    eldritch: ['void', 'darkness'],
    aura: ['energy', 'air'],
    aversion: ['soul', 'entropy'],
    beast: ['motion', 'life'],
    mind: ['fire', 'soul'],
    desire: ['soul', 'void'],
    undead: ['motion', 'death'],
    craft: ['exchange', 'tool'],
    cold: ['fire', 'entropy'],
    plant: ['life', 'earth'],
    man: ['soul', 'life'],
    tool: ['metal', 'energy'],
    light: ['air', 'fire'],
    mechanism: ['motion', 'tool'],
    metal: ['earth', 'order'],
    death: ['water', 'entropy'],
    motion: ['air', 'order'],
    exchange: ['entropy', 'order'],
    energy: ['order', 'fire'],
    protect: ['soul', 'earth'],
    senses: ['air', 'soul'],
    soul: ['life', 'death'],
    darkness: ['void', 'light'],
    void: ['air', 'entropy'],
    life: ['water', 'earth'],
    trap: ['motion', 'entropy'],
    taint: ['energy', 'entropy'],
    crystal: ['earth', 'air'],
    flight: ['air', 'motion'],
    electricity: ['energy', 'mechanism'],
    magnetism: ['metal', 'flight'],
    cheatiness: ['craft', 'greed'],
    radioactivity: ['light', 'energy'],
    stupidity: ['entropy', 'mind'],
  },
}

export const allAspects = [...gtnhAspectData.base, ...Object.keys(gtnhAspectData.compounds)]

export function getAspectName(key) {
  return aspectLabels[key] ?? key
}

export function getCanonicalAspect(keyOrTag) {
  return aspectKeysByTag[keyOrTag] ?? keyOrTag
}
